<h1> Types <h1>

### Int.
***

In [23]:
123 # integer literal

123

In [25]:
f'{123:08b}' # f string showing binary format

'01111011'

In [24]:
'123' # string ie text

'123'

In [19]:
type(123)   # the type is int

int

In [20]:
type(123.0) # decimal point number

float

In [29]:
45+67 #addition

112

In [27]:
45*67 # multiplication


3015

In [28]:
type(45-67) #subtration type

int

In [18]:

145 % 65 # modulos : giving remainder


15

In [22]:
45 / 67 # converted to float automaticaly 

0.6716417910447762

In [21]:
type (45 / 67) # division with floating point

float

In [30]:
145//67 # divison staying int

2

In [31]:
type(145//67) # division type.

int

<h3> Numpy<h3>


In [33]:
import pandas as pd
import numpy as np

In [36]:
L = [1, 2, 3] # data structure : list/array.

In [ ]:
L[[1, 2, 3], [4, 5, 6]] # 2 dementional array.

In [38]:
L = np.array ([[ 1, 2, 3], [ 4, 5, 6], [ 7, 8, 9]]) # n dementional array


In [39]:
print(L) # print L.


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
L.dtype # integer stored in 32 bytes.

dtype('int32')

In [45]:
np.random.randint(1, 7) # Generate a value 1 to 6 which is int, high number not inc

3

In [52]:
# Roll a dice 1000 times.
rolls = np.random.randint(1, 7, 1000)

In [53]:
# Average roll. 
np.mean(rolls)

3.552

In [54]:
# Spread. (standard deviation)
np.std(rolls)

1.703906100699214

In [56]:
# Likert scale. (survey eg agree/somewhat agree)
likert = np.random.randint(1, 8, 1000)

In [57]:
np.mean(likert)

3.998

In [58]:
# Median
np.median(likert)

4.0

***
### End