<h1> Types <h1>

### Int.
***

In [23]:
123 # integer literal

123

In [25]:
f'{123:08b}' # f string showing binary format

'01111011'

In [24]:
'123' # string ie text

'123'

In [19]:
type(123)   # the type is int

int

In [20]:
type(123.0) # decimal point number

float

In [29]:
45+67 #addition

112

In [27]:
45*67 # multiplication


3015

In [28]:
type(45-67) #subtration type

int

In [18]:

145 % 65 # modulos : giving remainder


15

In [22]:
45 / 67 # converted to float automaticaly 

0.6716417910447762

In [21]:
type (45 / 67) # division with floating point

float

In [30]:
145//67 # divison staying int

2

In [31]:
type(145//67)

int

***
### End.

<h2> Numpy<h2>


In [15]:
import pandas as pd
import numpy as np

In [16]:
L = np.array ([[ 1, 2, 3], [ 4, 5, 6], [ 7, 8, 9]])


In [ ]:

L = np.array ([[ 1, 2, 3], [ 4, 5, 6], [ 7, 8, 9]])


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
L.dtype

dtype('int32')

In [ ]:
np.array (1, 7)

NameError: name 'numpy' is not defined

### End