<h1> Types <h1>

<h2> Numpy<h2>


In [15]:
import pandas as pd
import numpy as np

In [16]:
L = np.array ([[ 1, 2, 3], [ 4, 5, 6], [ 7, 8, 9]])


In [ ]:

L = np.array ([[ 1, 2, 3], [ 4, 5, 6], [ 7, 8, 9]])


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
L.dtype

dtype('int32')

In [ ]:
np.array (1, 7)

NameError: name 'numpy' is not defined

### End